### ISSUE TITLE
RuntimeError when applying argmax to an empty tensor in deyo.py line 154

### ISSUE THREAD

**Issue by VivaLaVida10** [Jhyun17/DeYO#1]
### Description
Dear maintainers:
I've encountered a potential problem in `deyo.py` on line [154:](https://github.com/Jhyun17/DeYO/blob/1b76a3543607f7a8b635bee76699b70f54d0b588/methods/deyo.py#L154)

https://github.com/Jhyun17/DeYO/blob/1b76a3543607f7a8b635bee76699b70f54d0b588/methods/deyo.py#L154

When `filter_ids_2` filters out all elements from `prob_outputs`, attempting to use `argmax` results in a `RuntimeError` since the operation cannot be performed on an empty tensor. The error message is as follows:

```
RuntimeError: cannot perform reduction function argmax on a tensor with no elements because the operation does not have an identity.
```

### Suggested Fix
It may be beneficial to include a check before the `argmax` operation to ensure that the tensor is not empty. A possible fix is as follows:
```python
        if filter_ids_2[0].numel() > 0:
            corr_pl_2 = (targets[filter_ids_1][filter_ids_2] == prob_outputs[filter_ids_2].argmax(dim=1)).sum().item()
        else:   
            corr_pl_2 = 0
```

---
I hope this information is helpful, and I would appreciate any guidance or fixes you could provide.
Thank you for your time and assistance.
Best regards

**Comment by Jhyun17** [comment]
Thank you for reporting the error!
Following your advice, I modified the code to exit when final_backward is 0.
Please let me know if the error still occurs.

**Comment by VivaLaVida10** [comment]
Thank you for the quick fix! I've tried the new code and believe the issue is resolved. Also, I really appreciate the contributions your paper has made to the field.
